In [ ]:
# https://www.kaggle.com/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store/data

In [1]:
import pandas as pd

In [2]:
data_path = "/home/lpascual/Projects/E-Commerce_DWH/data/2019-Oct-subset-10p.csv"
#data_path = "/home/lpascual/Projects/E-Commerce_DWH/data/2019-Oct.csv"
df = pd.read_csv(data_path)
df.head(5)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [ ]:
# Event Types
df["event_type"].drop_duplicates()

0          view
162    purchase
331        cart
Name: event_type, dtype: object

In [ ]:
# Users that have multiple events
df_user_count = df.groupby("user_id").size()
df_user_count[df_user_count > 1]

user_id
208669541     2
244951053     5
255544096     6
260013793    23
277067319     6
             ..
556650809     3
556650814     2
556650858     2
556651002     2
556651065     2
Length: 382308, dtype: int64

In [ ]:
df[df["user_id"] == 244951053]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
387798,2019-10-01 08:47:35 UTC,view,1003535,2053013555631882655,electronics.smartphone,samsung,460.50,244951053,91769fdf-461b-4e43-9c73-88a07481b75c
388850,2019-10-01 08:48:28 UTC,view,1003535,2053013555631882655,electronics.smartphone,samsung,460.50,244951053,91769fdf-461b-4e43-9c73-88a07481b75c
2489108,2019-10-03 03:06:18 UTC,view,1005105,2053013555631882655,electronics.smartphone,apple,1415.48,244951053,ac5e27ca-6408-47ab-9837-19893a0334c2
2489969,2019-10-03 03:07:42 UTC,view,1004659,2053013555631882655,electronics.smartphone,samsung,731.04,244951053,ac5e27ca-6408-47ab-9837-19893a0334c2
2490422,2019-10-03 03:08:27 UTC,view,1004659,2053013555631882655,electronics.smartphone,samsung,731.04,244951053,ac5e27ca-6408-47ab-9837-19893a0334c2

In [11]:
df[df["event_type"] == "purchase"].head(5)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
162,2019-10-01 00:02:14 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,8187d148-3c41-46d4-b0c0-9c08cd9dc564
308,2019-10-01 00:04:37 UTC,purchase,1002532,2053013555631882655,electronics.smartphone,apple,642.69,551377651,3c80f0d6-e9ec-4181-8c5c-837a30be2d68
379,2019-10-01 00:06:02 UTC,purchase,5100816,2053013553375346967,NaN,xiaomi,29.51,514591159,0e5dfc4b-2a55-43e6-8c05-97e1f07fbb56
442,2019-10-01 00:07:07 UTC,purchase,13800054,2053013557418656265,furniture.bathroom.toilet,santeri,54.42,555332717,1dea3ee2-2ded-42e8-8e7a-4e2ad6ae942f
574,2019-10-01 00:09:26 UTC,purchase,4804055,2053013554658804075,electronics.audio.headphone,apple,189.91,524601178,2af9b570-0942-4dcd-8f25-4d84fba82553

In [ ]:
# Event history for a given User
df[df["user_id"] == 543272936]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
129,2019-10-01 00:01:46 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,8187d148-3c41-46d4-b0c0-9c08cd9dc564
162,2019-10-01 00:02:14 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,8187d148-3c41-46d4-b0c0-9c08cd9dc564
201,2019-10-01 00:02:48 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,8187d148-3c41-46d4-b0c0-9c08cd9dc564
218,2019-10-01 00:03:02 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,8187d148-3c41-46d4-b0c0-9c08cd9dc564
57666,2019-10-01 03:41:58 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,3591a683-59b0-41d0-94b7-fbc381401119
58225,2019-10-01 03:42:37 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,3591a683-59b0-41d0-94b7-fbc381401119
58698,2019-10-01 03:43:11 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,3591a683-59b0-41d0-94b7-fbc381401119
58724,2019-10-01 03:43:13 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,3591a683-59b0-41d0-94b7-fbc381401119
945174,2019-10-01 16:22:44 UTC,view,27201422,2053013564154708873,NaN,xiaomi,24.45,543272936,b43d10fa-4866-4d75-a13e-1d1829ff3040
949429,2019-10-01 16:25:17 UTC,view,27201309,2053013564154708873,NaN,kari,5.12,543272936,b43d10fa-4866-4d75-a13e-1d1829ff3040
1226189,2019-10-01 21:36:27 UTC,view,35108590,2070005009382114061,apparel.underwear,milavitsa,12.85,543272936,c4437e54-9146-4a51-861e-46eb8aa04fc9
1226288,2019-10-01 21:36:50 UTC,view,35101042,2070005009382114061,apparel.underwear,milavitsa,28.31,543272936,c4437e54-9146-4a51-861e-46eb8aa04fc9
1226652,2019-10-01 21:38:47 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,0cde3313-dbfe-4ba9-b1c4-e39f9de3a833
1247843,2019-10-02 00:25:09 UTC,view,49400037,2134905045613805589,NaN,NaN,151.87,543272936,8718c327-6e40-41f9-9b70-20ee6d950d1f
1248152,2019-10-02 00:26:48 UTC,view,49400001,2134905045613805589,NaN,NaN,159.59,543272936,8718c327-6e40-41f9-9b70-20ee6d950d1f
1248801,2019-10-02 00:30:43 UTC,view,44500006,2144356630513320518,NaN,omabelle,1673.14,543272936,8718c327-6e40-41f9-9b70-20ee6d950d1f
1248906,2019-10-02 00:31:25 UTC,view,41300094,2091727629378912491,NaN,NaN,66.26,543272936,8718c327-6e40-41f9-9b70-20ee6d950d1f
1249000,2019-10-02 00:32:09 UTC,view,46400010,2110937219005940617,apparel.trousers,sly,39.62,543272936,8718c327-6e40-41f9-9b70-20ee6d950d1f
1249700,2019-10-02 00:36:33 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,4ab63ddd-717a-435b-93cd-934176ecfc0e
1249966,2019-10-02 00:38:12 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,4ab63ddd-717a-435b-93cd-934176ecfc0e
1250124,2019-10-02 00:39:03 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,4ab63ddd-717a-435b-93cd-934176ecfc0e
1250477,2019-10-02 00:41:03 UTC,view,11300010,2053013555531219353,electronics.telephone,panasonic,40.39,543272936,d5de376a-9d8a-4e66-9fcd-74d00a384daa
1250694,2019-10-02 00:42:13 UTC,view,11300010,2053013555531219353,electronics.telephone,panasonic,40.39,543272936,d5de376a-9d8a-4e66-9fcd-74d00a384daa
1251001,2019-10-02 00:43:45 UTC,purchase,11300010,2053013555531219353,electronics.telephone,panasonic,40.39,543272936,d5de376a-9d8a-4e66-9fcd-74d00a384daa
1251252,2019-10-02 00:45:07 UTC,view,11300046,2053013555531219353,electronics.telephone,panasonic,51.83,543272936,d5de376a-9d8a-4e66-9fcd-74d00a384daa
1251677,2019-10-02 00:47:12 UTC,view,11300046,2053013555531219353,electronics.telephone,panasonic,51.83,543272936,d5de376a-9d8a-4e66-9fcd-74d00a384daa
1251774,2019-10-02 00:47:39 UTC,view,11300010,2053013555531219353,electronics.telephone,panasonic,40.39,543272936,d5de376a-9d8a-4e66-9fcd-74d00a384daa
2427629,2019-10-02 22:37:37 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,5fa53005-2891-4880-a4ac-aa039b71c37c
2428088,2019-10-02 22:42:22 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,5fa53005-2891-4880-a4ac-aa039b71c37c
2443535,2019-10-03 00:54:32 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,79ac06be-567a-45b6-a806-6863824d5355
2444066,2019-10-03 00:57:17 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,79ac06be-567a-45b6-a806-6863824d5355
2444238,2019-10-03 00:58:07 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,79ac06be-567a-45b6-a806-6863824d5355
2444334,2019-10-03 00:58:35 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,79ac06be-567a-45b6-a806-6863824d5355
2444405,2019-10-03 00:58:54 UTC,view,1005073,2053013555631882655,electronics.smartphone,samsung,1176.35,543272936,79ac06be-567a-45b6-a806-6863824d5355
2444595,2019-10-03 00:59:47 UTC,view,1005073,2053013555631882655,electronics.smartphone,samsung,1176.35,543272936,79ac06be-567a-45b6-a806-6863824d5355
2445350,2019-10-03 01:03:05 UTC,view,1005073,2053013555631882655,electronics.smartphone,samsung,1176.35,543272936,79ac06be-567a-45b6-a806-6863824d5355
2445419,2019-10-03 01:03:28 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,79ac06be-567a-45b6-a806-6863824d5355
2445658,2019-10-03 01:04:31 UTC,view,13300562,2053013557166998015,NaN,sonel,90.09,543272936,79ac06be-567a-45b6-a806-6863824d5355
2445853,2019-10-03 01:05:24 UTC,view,13300562,2053013557166998015,NaN,sonel,90.09,543272936,79ac06be-567a-45b6-a806-6863824d5355
2446064,2019-10-03 01:06:23 UTC,view,15700033,2053013559733912211,NaN,NaN,197.95,543272936,79ac06be-567a-45b6-a806-6863824d5355
3175604,2019-10-03 15:05:55 UTC,view,1004870,2053013555631882655,electronics.smartphone,samsung,291.08,543272936,3cbc757a-fcd2-431d-90b1-e99c95d4ed92
3175702,2019-10-03 15:06:00 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,132.15,543272936,3cbc757a-fcd2-431d-90b1-e99c95d4ed92
3179981,2019-10-03 15:09:14 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,132.15,543272936,3cbc757a-fcd2-431d-90b1-e99c95d4ed92
3180785,2019-10-03 15:09:50 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,132.15,543272936,3cbc757a-fcd2-431d-90b1-e99c95d4ed92
3548346,2019-10-03 22:00:30 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,4444f79b-3933-42f4-bcaf-12b96a0f8d31
3548412,2019-10-03 22:00:49 UTC,view,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,4444f79b-3933-42f4-bcaf-12b96a0f8d31

In [ ]:
# Purchase behavior of a User
df[(df["user_id"] == 543272936) & (df["event_type"] == "purchase")]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
162,2019-10-01 00:02:14 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,8187d148-3c41-46d4-b0c0-9c08cd9dc564
58225,2019-10-01 03:42:37 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,3591a683-59b0-41d0-94b7-fbc381401119
1249966,2019-10-02 00:38:12 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,4ab63ddd-717a-435b-93cd-934176ecfc0e
1251001,2019-10-02 00:43:45 UTC,purchase,11300010,2053013555531219353,electronics.telephone,panasonic,40.39,543272936,d5de376a-9d8a-4e66-9fcd-74d00a384daa
2428088,2019-10-02 22:42:22 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,5fa53005-2891-4880-a4ac-aa039b71c37c
2444066,2019-10-03 00:57:17 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,130.25,543272936,79ac06be-567a-45b6-a806-6863824d5355
3179981,2019-10-03 15:09:14 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,132.15,543272936,3cbc757a-fcd2-431d-90b1-e99c95d4ed92

In [ ]:
df[((df["event_type"] == "cart") | (df["event_type"] == "purchase"))].sort_values(by=["user_id", "product_id"])

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
2988593,2019-10-03 11:59:28 UTC,purchase,9300037,2053013554524586339,NaN,lg,200.52,340041246,c0c5b9c2-29bb-43ff-98f0-6a53abd70d50
131496,2019-10-01 05:02:50 UTC,cart,1004739,2053013555631882655,electronics.smartphone,xiaomi,197.52,386070015,49d03116-3c95-4e13-8b9c-e3be97551fe8
2179585,2019-10-02 16:27:47 UTC,cart,5100503,2053013553375346967,NaN,xiaomi,23.14,393318901,7a4f46a7-7141-424a-9eee-5a063da9c284
2179593,2019-10-02 16:27:48 UTC,cart,5100503,2053013553375346967,NaN,xiaomi,23.14,393318901,7a4f46a7-7141-424a-9eee-5a063da9c284
2183651,2019-10-02 16:30:33 UTC,cart,5100767,2053013553375346967,NaN,samsung,30.61,393318901,7a4f46a7-7141-424a-9eee-5a063da9c284
474371,2019-10-01 09:59:42 UTC,cart,1801881,2053013554415534427,electronics.video.tv,samsung,506.29,393619196,ed5d037e-be8c-4c94-a8b3-ec881eecdb33
474578,2019-10-01 09:59:54 UTC,cart,1801881,2053013554415534427,electronics.video.tv,samsung,506.29,393619196,ed5d037e-be8c-4c94-a8b3-ec881eecdb33
3759309,2019-10-04 05:15:25 UTC,cart,1004461,2053013555631882655,electronics.smartphone,xiaomi,239.36,417754567,4d360dee-9cde-44c6-aa62-65a66dd78b06
3733240,2019-10-04 04:52:00 UTC,cart,2601936,2053013563970159485,NaN,dauscher,483.90,422006171,388f93b3-f55b-46bf-b670-9dd42dec79a2
1386513,2019-10-02 04:38:34 UTC,purchase,2501202,2053013564003713919,appliances.kitchen.oven,midea,321.73,433754231,33967e3f-8589-414b-a4d9-8421afb603e7

In [16]:
df[df["user_id"] == 393318901]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
2178852,2019-10-02 16:27:16 UTC,view,5100503,2053013553375346967,NaN,xiaomi,23.14,393318901,7a4f46a7-7141-424a-9eee-5a063da9c284
2179585,2019-10-02 16:27:47 UTC,cart,5100503,2053013553375346967,NaN,xiaomi,23.14,393318901,7a4f46a7-7141-424a-9eee-5a063da9c284
2179593,2019-10-02 16:27:48 UTC,cart,5100503,2053013553375346967,NaN,xiaomi,23.14,393318901,7a4f46a7-7141-424a-9eee-5a063da9c284
2183291,2019-10-02 16:30:17 UTC,view,5100767,2053013553375346967,NaN,samsung,30.61,393318901,7a4f46a7-7141-424a-9eee-5a063da9c284
2183651,2019-10-02 16:30:33 UTC,cart,5100767,2053013553375346967,NaN,samsung,30.61,393318901,7a4f46a7-7141-424a-9eee-5a063da9c284
2187241,2019-10-02 16:32:56 UTC,view,5100767,2053013553375346967,NaN,samsung,30.61,393318901,7a4f46a7-7141-424a-9eee-5a063da9c284